# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb8ee9d39367015e41a70a902a297c716e064a8691b121863fe663718adca271d09cd153348d9b4fff8c096613ced10e17d11e3f9f7f94c2cb0a95fa8e0e3cdb

test:
  secret_key_base: 5cfb27c0795f4d29f7b000a937c492bd7add4a1f8cd6b5fcf4d1429e84a6a6d658967e95d7141d40914eea64fc8b4a46db6e8e40e71a335b9731459ab37915b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
